name: Convert Figma → Flutter

on:
  workflow_dispatch:
    inputs:
      figma_file_key:
        description: 'Figma File Key'
        required: true
      figma_token:
        description: 'Figma Personal Access Token'
        required: true
      project_name:
        description: 'Project name (used as folder)'
        required: true

jobs:
  parabeac:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Clone Parabeac Core
        run: git clone https://github.com/Parabeac/parabeac-core.git parabeac

      - name: Generate Flutter for ${{ github.event.inputs.project_name }}
        run: |
          mkdir -p generated/${{ github.event.inputs.project_name }}
          dart parabeac/lib/parabeac.dart \
            -f ${{ github.event.inputs.figma_file_key }} \
            -k ${{ github.event.inputs.figma_token }} \
            -o generated/${{ github.event.inputs.project_name }}

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add generated/${{ github.event.inputs.project_name }}
          git commit -m "chore: auto-generate Flutter for ${{ github.event.inputs.project_name }}"
          git push
