name: Convert Figma → Flutter

on:
  workflow_dispatch:
    inputs:
      figma_file_key:
        description: 'Figma File Key'
        required: true
      figma_token:
        description: 'Figma Personal Access Token'
        required: true
      project_name:
        description: 'Project name (used as folder)'
        required: true

jobs:
  parabeac:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Dart 2.x (compatible with Parabeac Core)    # ← THIS IS THE CHANGE
        uses: dart-lang/setup-dart@v1
        with:
          sdk: '2.19.6'                                        # ← pin to 2.19.6

      - name: Clone Parabeac Core
        run: |
          git clone https://github.com/Parabeac/parabeac-core.git parabeac

      - name: Install Parabeac dependencies
        run: |
          cd parabeac
          dart pub get

      - name: Generate Flutter for ${{ github.event.inputs.project_name }}
        run: |
          mkdir -p generated/${{ github.event.inputs.project_name }}
          dart --enable-asserts parabeac/parabeac.dart \
            -f ${{ github.event.inputs.figma_file_key }} \
            -k ${{ github.event.inputs.figma_token }} \
            -o generated/${{ github.event.inputs.project_name }}

      - name: Commit & push generated code
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add generated/${{ github.event.inputs.project_name }}
          git commit -m "chore: auto-generate Flutter for ${{ github.event.inputs.project_name }}"
          git push
